version: "3"
services:
    php:
        image: php:7.2-apache
        ports:
            - "8001:80"
        volumes:
            - ./src:/var/www/html/
        links:
            - mysql
        networks:
            - default
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - "8000:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_USER: root
            PMA_PASSWORD: root
volumes:
    persistent:
